# Generated by Django 4.2.6 on 2024-04-15 09:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True, verbose_name='Kategoriya')),
            ],
            options={
                'verbose_name': 'Kategoriya',
                'verbose_name_plural': 'Kategoriyalar',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='users/')),
                ('status', models.CharField(blank=True, max_length=150, null=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('phone', models.CharField(blank=True, max_length=13, null=True)),
                ('mobile', models.CharField(blank=True, max_length=13, null=True)),
                ('sayt', models.URLField(blank=True, null=True)),
                ('github', models.CharField(blank=True, max_length=25, null=True)),
                ('telegram', models.CharField(blank=True, max_length=25, null=True)),
                ('instagram', models.CharField(blank=True, max_length=25, null=True)),
                ('facebook', models.CharField(blank=True, max_length=25, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Maqola nomi')),
                ('content', models.TextField(blank=True, null=True, verbose_name='Matni')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Kiritilgan vaqti')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Tahrirlangan vaqti')),
                ('published', models.BooleanField(default=True, verbose_name='Saytga chiqarish')),
                ('views', models.IntegerField(default=0, verbose_name="Ko'rishlar soni")),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.category', verbose_name='Kategoriya')),
            ],
            options={
                'verbose_name': 'Maqola',
                'verbose_name_plural': 'Maqolalar',
                'ordering': ('-pk',),
            },
        ),
    ]
